




public class PromptGenerator
{
    List<string> _prompts = new List<string>()
    {
    "Who was the most interesting person I interacted with today?",
    "What was the best part of my day?",
    "How did I see the hand of the Lord in my life today?",
    "What was the strongest emotion I felt today?",
    "If I had one thing I could do over today, what would it be?",
    "What made me smile today?",
    "What is something new I learned today?",
    "Did I help someone today? How?",
    "What was the most challenging part of my day?",
    "What am I grateful for today?",
    "How did I step out of my comfort zone today?",
    "What was an unexpected moment of joy?",
    "Did I face any fears today?",
    "What was my biggest distraction today?",
    "If I could describe today in one word, what would it be?",
    "What is something I wish I had done differently today?",
    "Did I spend my time wisely today?",
    "What is one thing I accomplished today that I’m proud of?",
    "What is one thing I want to improve on tomorrow?",
    "What was my favorite conversation today?",
    "How did I practice self-care today?",
    "What moment today do I want to remember forever?",
    "Did I meet someone new today?",
    "What is one thing I learned about myself today?",
    "What was a small victory I had today?",
    "How did I show kindness today?",
    "Did I feel productive today? Why or why not?",
    "What is one thing that made me laugh today?",
    "What was the best decision I made today?",
    "What is one thing I wish I could tell my past self about today?",
    "How did I express creativity today?",
    "What book, movie, or show did I enjoy today?",
    "How did I take care of my body today?",
    "What was the weather like today? Did it affect my mood?",
    "What was a challenge I overcame today?",
    "Did I receive any compliments today? How did they make me feel?",
    "What inspired me today?",
    "What was a random thought I had today?",
    "If I had an extra hour today, what would I have done?",
    "What goal did I work towards today?",
    "Did I practice patience today? How?",
    "What is one thing I want to dream about tonight?",
    "Did I experience any moments of peace today?",
    "What song or music resonated with me today?",
    "Did I witness an act of kindness today?",
    "What’s something I’m looking forward to tomorrow?",
    "If today was a chapter in my life story, what would the title be?",
    "Did I feel loved today? How?",
    "What was something that surprised me today?",
    "How did I handle stress today?",
    "Did I face any rejections today? How did I respond?",
    "What is one thing that energized me today?",
    "How did I show gratitude today?",
    "What is one thing I saw today that was beautiful?",
    "Did I have any moments of self-doubt today?",
    "What personal strength did I use today?",
    "If today had a theme song, what would it be?",
    "Did I step outside of my comfort zone today?",
    "What was a mistake I made today? What did I learn from it?",
    "Did I practice forgiveness today?",
    "What was a highlight from my work or studies today?",
    "Did I have a meaningful connection with someone today?",
    "What is one thing I did today that my future self will thank me for?",
    "How did I challenge myself today?",
    "What was a thought or idea that stood out to me today?",
    "Did I spend quality time with loved ones today?",
    "What was something that tested my patience today?",
    "Did I learn anything new about a friend or family member today?",
    "What is one thing I need to let go of from today?",
    "How did I express love today?",
    "Did I have any moments of self-reflection today?",
    "What is one thing that made me feel strong today?",
    "Did I take any risks today? What was the outcome?",
    "How did I handle a difficult situation today?",
    "What habit did I work on today?",
    "What was the last thing I thought about before sleeping yesterday?",
    "What is one thing I’m curious about right now?",
    "How did I feel when I woke up this morning?",
    "What advice would I give myself if I could go back to this morning?",
    "Did I have any dreams last night? What do I remember?",
    "What is something I appreciate about myself today?",
    "How did I spend my free time today?",
    "Did I accomplish everything I wanted to today?",
    "What’s one thing I wish more people knew about me?",
    "What was a moment today where I felt truly present?",
    "Did I feel any moments of jealousy today? Why?",
    "What was a decision I made today that felt right?",
    "If I could relive one moment from today, what would it be?",
    "What is something I felt guilty about today?",
    "Did I take time to enjoy the little things today?",
    "How did I take a break today?",
    "What is one thing I can do to make tomorrow better?",
    "Did I have any ‘aha’ moments today?",
    "What was something I did today that required courage?",
    "Did I experience any moments of nostalgia today?",
    "What was the most peaceful part of my day?",
    "If I had to teach someone one lesson from today, what would it be?",
    "Did I say something today that I regret?",
    "What’s one thing I want to remind myself of every day?",
    "How did I make someone else's day better today?",
    "Did I feel connected to something greater than myself today?"
};


    public string GetPrompt ()
    {
        Random randomPrompt = new Random();
        int index = randomPrompt.Next(_prompts.Count);
        return _prompts[index];
    }
}